from pyspark.sql.types import *

youtube_schema = StructType([
    StructField("video_id", StringType()),
    StructField("video_published_at", TimestampType()),
    StructField("video_trending_date", DateType()),
    StructField("video_trending_country", StringType()),
    StructField("video_title", StringType()),
    StructField("video_description", StringType()),
    StructField("video_default_thumbnail", StringType()),
    StructField("video_category_id", IntegerType()),
    StructField("video_tags", StringType()),
    StructField("video_duration", StringType()),
    StructField("video_dimension", StringType()),
    StructField("video_definition", StringType()),
    StructField("video_licensed_content", BooleanType()),
    StructField("video_view_count", LongType()),
    StructField("video_like_count", LongType()),
    StructField("video_comment_count", LongType()),
    StructField("channel_id", StringType()),
    StructField("channel_title", StringType()),
    StructField("channel_description", StringType()),
    StructField("channel_custom_url", StringType()),
    StructField("channel_published_at", TimestampType()),
    StructField("channel_country", StringType()),
    StructField("channel_view_count", LongType()),
    StructField("channel_subscriber_count", LongType()),
    StructField("channel_have_hidden_subscribers", BooleanType()),
    StructField("channel_video_count", LongType()),
    StructField("channel_localized_title", StringType()),
    StructField("channel_localized_description", StringType())
])
